// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var services = [
  {
    title: "Comunicaci\xF3n interna",
    desc: "Diagnosticamos c\xF3mo te est\xE1s comunicando en la interna y definimos una estrategia y plan de acci\xF3n. Nos ocupamos desde la planificaci\xF3n estrat\xE9gica hasta la ejecuci\xF3n de cada campa\xF1a."
  },
  {
    title: "Dise\xF1o gr\xE1fico",
    desc: "Somos el dise\xF1ador de tu empresa. Desde una identidad hasta un mailing, cubrimos cualquier necesidad de dise\xF1o."
  },
  {
    title: "Comunicaci\xF3n digital",
    desc: "Comunicamos tu marca de forma coherente en todos los puntos de contacto: contenido para redes, influencers, pauta digital."
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List the communication and design services offered by Happen.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_info_default = defineTool2({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return Happen's public contact information (website, email, social handles).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "Happen",
      website: "https://somoshappen.com",
      instagram: "@somoshappen"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "happen-mcp",
  title: "Happen MCP",
  version: "0.1.0",
  instructions: "Tools for the Happen agency site. Use `list_services` to enumerate services and `get_contact_info` for public contact details.",
  tools: [list_services_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
